#!/bin/bash

if [ $1 ] ; then							# 6 random digits
	for i in {0..5}; do
		printf -v hex1 '%x' $((RANDOM%16))
		printf -v hex2 '%x' $((RANDOM%16))
		printf -v hex3 '%x' $((RANDOM%16))
		printf -v hex4 '%x' $((RANDOM%16))
		printf -v hex5 '%x' $((RANDOM%16))
		printf -v hex6 '%x' $((RANDOM%16))
		i2cledcontrol $i $hex1$hex2$hex3$hex4$hex5$hex6
	done
else										# 3 rgb values
	for i in {0..5}; do
		printf -v hex1 %x $((RANDOM%240+16))
		printf -v hex2 %x $((RANDOM%240+16))
		printf -v hex3 %x $((RANDOM%240+16))
		i2cledcontrol $i $hex1$hex2$hex3
	done
fi
